api_keys:
  # Format: provider: {"env_var": "ENV_VAR_NAME", "key": "your_key_here"}
  anthropic:
    env_var: "ANTHROPIC_API_KEY"
    key: "default_anthropic_key_replace_me"
  openai:
    env_var: "OPENAI_API_KEY"
    key: "default_openai_key_replace_me"
  google:
    env_var: "GOOGLE_API_KEY"
    key: "default_google_key_replace_me"
  together:
    env_var: "TOGETHER_API_KEY"
    key: "default_together_key_replace_me"
  mistral:
    env_var: "MISTRAL_API_KEY"
    key: "default_mistral_key_replace_me"
  huggingface:
    env_var: "HUGGINGFACE_API_KEY"
    key: "default_huggingface_key_replace_me"
