models:
  "claude-opus":
    provider: "anthropic"
    model_id: "claude-3-opus-20240229"
    description: "Claude 3 Opus model"

  "claude-sonnet":
    provider: "anthropic"
    model_id: "claude-3-sonnet-20240229"
    description: "Claude 3 Sonnet model"

  "gpt-4":
    provider: "openai"
    model_id: "gpt-4"
    description: "GPT-4 model"

  "gemini-pro":
    provider: "google"
    model_id: "gemini-pro"
    description: "Google's Gemini Pro model"

  "mistral-large":
    provider: "mistral"
    model_id: "mistral-large-2407"
    description: "Mistral's large model"
